### ISSUE TITLE
Probléme avec esx_textUI

### ISSUE THREAD

**Issue by PandaSw** [EXODEcola/es_extended-en-DoubleJobs#1]
Quand je veux rentré dans un appartment acheter avec esx_property j'ai une erreur : script error : esx_property/client/main.lua:779: attempt to call a nil value (field 'TextUI'). J'ai fait un test croisé avec un es_extended classique et pas d'erreur. Si vous savez d'ou cela peut venir.

**Comment by exoxecola** [comment]
Demandé moi en amies sur discord que l’on puis voir cela en voc toto.mass

**Comment by PandaSw** [comment]
J'ai essayé de t'ajouter mais tu n'accepte pas les invitations discord. Rejoins moi sur ce discord se seras plus simple :  https://discord.gg/A69ZYKY5kt

**Comment by PandaSw** [comment]
Résolution pour le 1.10.2 esx_textui est buggé dans  cette version de esx_core . Passez directement a la 1.10.5 ou 1.10.6.
